pipeline {
    agent any
    stages {
        stage("Build") {
            agent {
                docker { image "openjdk:8u312-jdk" }
            }
            steps {
                dir("sample-app") {
                    sh "./mvnw clean package -DskipTests"
                }
            }
        }
    }
}
