apiVersion: v1
kind: Secret
metadata:
  name: sample-domain-weblogic-credentials
  labels:
    weblogic.domainUID: sample-domain
type: Opaque
data: # admin:admin123
  password: YWRtaW4xMjM=
  username: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-domain-runtime-encryption-secret
  labels:
    weblogic.domainUID: sample-domain
type: Opaque
data: # secret
  password: c2VjcmV0

